/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Server1;

/**
 *
 * @author Student
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
     
        
    }
    public int game(){
    
        //123
        int flag =22;   
       if(jButton1.getText().equals("0") && jButton2.getText().equals("0") && jButton3.getText().equals("0")){
           flag=0;
       }
       else if(jButton1.getText().equals("*") && jButton2.getText().equals("*") && jButton3.getText().equals("*")){
           flag=1;
       }
       
       //456
       else if(jButton4.getText().equals("0") && jButton5.getText().equals("0") && jButton6.getText().equals("0")){
           flag=0;
       }
       else if(jButton4.getText().equals("*") && jButton5.getText().equals("*") && jButton6.getText().equals("*")){
           flag=1;
       }
       
        //789
       else if(jButton7.getText().equals("0") && jButton8.getText().equals("0") && jButton9.getText().equals("0")){
           flag=0;
       }
       else if(jButton7.getText().equals("*") && jButton8.getText().equals("*") && jButton9.getText().equals("*")){
           flag=1;
       }
       
       
       
       ///147
        
       else if(jButton1.getText().equals("0") && jButton4.getText().equals("0") && jButton7.getText().equals("0")){
           flag=0;
       }
       else if(jButton1.getText().equals("*") && jButton4.getText().equals("*") && jButton7.getText().equals("*")){
           flag=1;
       }
       
       
       //259
       
        
       else if(jButton2.getText().equals("0") && jButton5.getText().equals("0") && jButton8.getText().equals("0")){
           flag=0;
       }
       else if(jButton2.getText().equals("*") && jButton5.getText().equals("*") && jButton8.getText().equals("*")){
           flag=1;
       }
       
       
       //369
        
       else if(jButton3.getText().equals("0") && jButton6.getText().equals("0") && jButton9.getText().equals("0")){
           flag=0;
       }
       else if(jButton3.getText().equals("*") && jButton6.getText().equals("*") && jButton9.getText().equals("*")){
           flag=1;
       }
       
       //159
        
       if(jButton1.getText().equals("0") && jButton5.getText().equals("0") && jButton9.getText().equals("0")){
          flag=0;
          
       }
       else if(jButton1.getText().equals("*") && jButton5.getText().equals("*") && jButton9.getText().equals("*")){
           flag=1;
       }
       
       
       //753
        
       if(jButton7.getText().equals("0") && jButton5.getText().equals("0") && jButton3.getText().equals("0")){
           flag=0;
       }
       else if(jButton7.getText().equals("*") && jButton5.getText().equals("*") && jButton3.getText().equals("*")){
           flag=1;
       }
       
       if(flag==0 || flag==1){
             jButton1.setEnabled(false);
          jButton2.setEnabled(false);
           jButton3.setEnabled(false);
            jButton4.setEnabled(false);
             jButton5.setEnabled(false);
              jButton6.setEnabled(false);
               jButton7.setEnabled(false);
                jButton8.setEnabled(false);
                 jButton9.setEnabled(false);
                 Couter.count=0;
       }
       
       
       return flag; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("TIC TAC TOC");

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton10.setText("Restart");
        jButton10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jButton1.setEnabled(false);
        
        if(Couter.count%2==0){
            jButton1.setText("0");
            Couter.count= Couter.count+1;
        }
        else if(Couter.count%2!=0){
            jButton1.setText("*");
            Couter.count= Couter.count+1;
        }
        
        
        
        
        
        if(game()==0 ){
            jLabel2.setText("Game By 0");
        }
        else if(game()==1){
            jLabel2.setText("Game By *");
        }
        else if(game()==22 && Couter.count==9){
             jLabel2.setText("Draw Game");
        }
            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jButton2.setEnabled(false);
        
        if(Couter.count%2==0){
            jButton2.setText("0");
            Couter.count= Couter.count+1;
        }
        else if(Couter.count%2!=0){
            jButton2.setText("*");
            Couter.count= Couter.count+1;
        }
        
        if(game()==0 ){
            jLabel2.setText("Game By 0");
        }
        else if(game()==1){
            jLabel2.setText("Game By *");
        }
        else if(game()==22 && Couter.count==9){
             jLabel2.setText("Draw Game");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jButton3.setEnabled(false);
        
        if(Couter.count%2==0){
            jButton3.setText("0");
            Couter.count= Couter.count+1;
        }
        else if(Couter.count%2!=0){
            jButton3.setText("*");
            Couter.count= Couter.count+1;
        }
        
        
        if(game()==0 ){
            jLabel2.setText("Game By 0");
        }
        else if(game()==1){
            jLabel2.setText("Game By *");
        }
        else if(game()==22 && Couter.count==9){
             jLabel2.setText("Draw Game");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jButton4.setEnabled(false);
        
        if(Couter.count%2==0){
            jButton4.setText("0");
            Couter.count= Couter.count+1;
        }
        else if(Couter.count%2!=0){
            jButton4.setText("*");
            Couter.count= Couter.count+1;
        }
        
        if(game()==0 ){
            jLabel2.setText("Game By 0");
        }
        else if(game()==1){
            jLabel2.setText("Game By *");
        }
        else if(game()==22 && Couter.count==9){
             jLabel2.setText("Draw Game");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jButton5.setEnabled(false);
        
        if(Couter.count%2==0){
            jButton5.setText("0");
            Couter.count= Couter.count+1;
        }
        else if(Couter.count%2!=0){
            jButton5.setText("*");
            Couter.count= Couter.count+1;
        }
        if(game()==0 ){
            jLabel2.setText("Game By 0");
        }
        else if(game()==1){
            jLabel2.setText("Game By *");
        }
        else if(game()==22 && Couter.count==9){
             jLabel2.setText("Draw Game");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jButton6.setEnabled(false);
        
        if(Couter.count%2==0){
            jButton6.setText("0");
            Couter.count= Couter.count+1;
        }
        else if(Couter.count%2!=0){
            jButton6.setText("*");
            Couter.count= Couter.count+1;
        }
        
        if(game()==0 ){
            jLabel2.setText("Game By 0");
        }
        else if(game()==1){
            jLabel2.setText("Game By *");
        }
        else if(game()==22 && Couter.count==9){
             jLabel2.setText("Draw Game");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jButton7.setEnabled(false);
        
        if(Couter.count%2==0){
            jButton7.setText("0");
            Couter.count= Couter.count+1;
        }
        else if(Couter.count%2!=0){
            jButton7.setText("*");
            Couter.count= Couter.count+1;
        }
        
        if(game()==0 ){
            jLabel2.setText("Game By 0");
        }
        else if(game()==1){
            jLabel2.setText("Game By *");
        }
        else if(game()==22 && Couter.count==9){
             jLabel2.setText("Draw Game");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        jButton8.setEnabled(false);
        
        if(Couter.count%2==0){
            jButton8.setText("0");
            Couter.count= Couter.count+1;
        }
        else if(Couter.count%2!=0){
            jButton8.setText("*");
            Couter.count= Couter.count+1;
        }
        
        if(game()==0 ){
            jLabel2.setText("Game By 0");
        }
        else if(game()==1){
            jLabel2.setText("Game By *");
        }
        else if(game()==22 && Couter.count==9){
             jLabel2.setText("Draw Game");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        
         jButton9.setEnabled(false);
         
        if(Couter.count%2==0){
            jButton9.setText("0");
            Couter.count= Couter.count+1;
        }
        else if(Couter.count%2!=0){
            jButton9.setText("*");
            Couter.count= Couter.count+1;
        }
        
        
        if(game()==0 ){
         
          jLabel2.setText("Game By 0");
            
        }
        else if(game()==1){
            jLabel2.setText("Game By *");
        }
        else if(game()==22 && Couter.count==9){
             jLabel2.setText("Draw Game");
        }
        
       
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         jButton1.setEnabled(true);
          jButton2.setEnabled(true);
           jButton3.setEnabled(true);
            jButton4.setEnabled(true);
             jButton5.setEnabled(true);
              jButton6.setEnabled(true);
               jButton7.setEnabled(true);
                jButton8.setEnabled(true);
                 jButton9.setEnabled(true);
                 Couter.count=0;
                 jButton1.setText(null);
                  jButton2.setText(null);
                   jButton3.setText(null);
                    jButton4.setText(null);
                     jButton5.setText(null);
                      jButton6.setText(null);
                       jButton7.setText(null);
                        jButton8.setText(null);
                         jButton9.setText(null);
                         jLabel2.setText(null);
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
